#ifndef PROCESSORPLUGIN_H
#define PROCESSORPLUGIN_H

#include <sofa/helper/system/config.h>

#define PROCESSORPLUGIN_MAJOR_VERSION \
  $ { PROCESSORPLUGIN_MAJOR_VERSION }
#define PROCESSORPLUGIN_MINOR_VERSION \
  $ { PROCESSORPLUGIN_MINOR_VERSION }
#ifdef SOFA_BUILD_PROCESSORPLUGIN
#define SOFA_TARGET PROCESSORPlugin
#define SOFA_PROCESSORPLUGIN_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#define SOFA_PROCESSORPLUGIN_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif

#endif  // PROCESSORPLUGIN_H
