#ifndef SOFAOROPENCVPLUGIN_H
#define SOFAOROPENCVPLUGIN_H

#include <sofa/helper/system/config.h>

#define SOFAOROPENCVPLUGIN_MAJOR_VERSION \
  $ { SOFAOROPENCVPLUGIN_MAJOR_VERSION }
#define SOFAOROPENCVPLUGIN_MINOR_VERSION \
  $ { SOFAOROPENCVPLUGIN_MINOR_VERSION }
#ifdef SOFA_BUILD_SOFAOROPENCVPLUGIN
#define SOFA_TARGET SofaOROpenCVPlugin
#define SOFA_SOFAOROPENCVPLUGIN_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#define SOFA_SOFAOROPENCVPLUGIN_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif

#endif  // SOFAOROPENCVPLUGIN_H
